name: Python CI

on:
  pull_request:
    branches: [main, dev, qa, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Run tests
      run: |
        echo "Run your tests here"
        # pytest or unittest
